---
title: "Mliyoni 2017 extension"
author: "sbsambado"
date: "6/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r DONT USEdensity dependent host tick metapopulation}
library(deSolve)

host.tick <- function(t, x, params) {
  S = x[1]
  X = x[2]
  
  T = x[3]
  Y = x[4]
  
  V = x[5] # total tick pop
  N = x[6] # total host pop
  
  beta = params[1]
  b = params[2]
  K = params[3]
  M = params[4]
  b = params[5]
  d = params[6]
  A_hat = params[7]
  A = params[8]
  v = params[9]
  
  dSdt = (b*V) - (b*((S*V)/(M*N))) - (A*((S*Y)/N)) - (d*S)
  dXdt = (A*((S*Y)/N)) - (b*((X*V)/M*N)) - (d*X)
  
  dTdt = (beta*N) - (beta*((T*N)/K)) - (A_hat*((T*X)/N)) - (b*T) + (v*Y)
  dYdt = (A_hat*((T*X)/N)) - (beta*((Y*N)/K)) - ((b + v)*Y)
  
  dVdt = (dSdt + dXdt)
  dNdt = (dTdt + dYdt)
  
  return(list(c(dSdt, dXdt, dTdt, dYdt, dVdt, dNdt)))
}
# tick
#V = S + X
S0 = 100 # susceptible tick
X0 = 1 # infected tick
V = 101 # tick pop v = s + x


# host
T0 = 20 # susceptible host
Y0 = 0 # infected host
N = 20 # host pop n = t + y

initial_values = c(S = S0, X = X0, V = V,
                   T = T0, Y = Y0, N = N)


# decent params, .2, .9, 300, 3000, .01, .01, .2, .7, .9
# .2, .75, 1200, 100, .01, .001, .005, .05, .51 for 1000, 125 and 1000 114
  beta = .02 # growth rate host
  b = 1 # growth rate ticks
  K = 25 # carrying capacity for hosts per m^2
  M = 100 # max number of ticks per host # OG 200
  b = 0.2 # natural mortality host
  d = 0.2 # natural mortality ticks # OG .01 
  A_hat = 0.08 # transmission rate from ticks to hosts #OG .02
  A = 0.05 # transmission rate from host to ticks # OG .07
  v = .6 # host recovery rate
  
parameters = c(beta, b, K, M, b, d, A_hat, A, v)

times = seq(0, 60, length.out = 10000)

results = lsoda(initial_values, times, host.tick, parameters)
head(results)

Scol = 'green'
Xcol = 'red'
Tcol = 'blue'
Ycol = 'orange'

plot(x = results[, "time"], y = results[, "S"], type = 'l', col=Scol, las = 1, lwd=2, xlab = 'Time', ylab = 'Number of Individuals', ylim = c(0,200),
     xlim = c(0,60),main = "Host - Tick Metapopulation Model")
lines(x = results[, "time"], y = results[, "X"], col = Xcol, lwd = 2)
lines(x = results[, "time"], y = results[, "T"], col = Tcol, lwd = 2)
lines(x = results[, "time"], y = results[, "Y"], col = Ycol, lwd = 2)
#lines(x = results[, "time"], y = results[, "V"], col = 'black', lwd = 2)
#lines(x = results[, "time"], y = results[, "N"], col = 'grey', lwd = 2)
legend('topright', legend = c('Tick, Uninfected (S)', 'Tick, Infected (X)', 'Host Uninfected (T)', 'Host Infected (Y)','Tick pop', 'Host pop'), col = c(Scol, Xcol, Tcol, Ycol, 'black', 'grey'),
       lwd = 2,cex = 0.9)


```


```{r DONT USE not density dependent}
library(deSolve)

host.tick <- function(t, x, params) {
  S = x[1]
  X = x[2]
  
  T = x[3]
  Y = x[4]
  
  V = x[5] # total tick pop
  N = x[6] # total host pop
  
  beta = params[1]
  b = params[2]
  K = params[3]
  M = params[4]
  b = params[5]
  d = params[6]
  A_hat = params[7]
  A = params[8]
  v = params[9]
  
  dSdt = (b*V) - ((b*S*V)/(M*N)) - ((A*S*Y)/N) - (d*S)
  dXdt = (A*((S*Y)/N)) - ((b*X*V)/M*N) - (d*X)
  
  dTdt = (beta*N) - ((beta*T*N)/K) - ((A_hat*T*X)/N) - (b*T) + (v*Y)
  dYdt = ((A_hat*T*X)/N) - ((beta*Y*N)/K) - ((b + v)*Y)
  
  dVdt = (dSdt + dXdt)
  dNdt = (dTdt + dYdt)
  
  return(list(c(dSdt, dXdt, dTdt, dYdt, dVdt, dNdt)))
}
# tick
#V = S + X
S0 = 1000 # susceptible tick
X0 = 225 # infected tick
V = 1225 # tick pop v = s + x


# host
T0 = 1000 # susceptible host
Y0 = 200 # infected host
N = 1200 # host pop n = t + y

initial_values = c(S = S0, X = X0, V = V,
                   T = T0, Y = Y0, N = N)


# decent params, .2, .9, 300, 3000, .01, .01, .2, .7, .9
# .2, .75, 1200, 100, .01, .001, .005, .05, .51 for 1000, 125 and 1000 114
  beta = .42 # growth rate host
  b = .95 # growth rate ticks
  K = 1200 # carrying capacity for hosts per m^2
  M = 100 # max number of ticks per host # OG 200
  b = 0.01 # natural mortality host
  d = 0.001 # natural mortality ticks # OG .01 
  A_hat = 0.002 # transmission rate from ticks to hosts #OG .02
  A = 0.002 # transmission rate from host to ticks # OG .07
  v = .91 # host recovery rate
  
parameters = c(beta, b, K, M, b, d, A_hat, A, v)

times = seq(0, 60, length.out = 10000)

results = lsoda(initial_values, times, host.tick, parameters)
head(results)

Scol = 'green'
Xcol = 'red'
Tcol = 'blue'
Ycol = 'orange'

plot(x = results[, "time"], y = results[, "S"], type = 'l', col=Scol, las = 1, lwd=2, xlab = 'Time', ylab = 'Number of Individuals', ylim = c(0,2500),
     xlim = c(0,60),main = "Host - Tick Metapopulation Model")
lines(x = results[, "time"], y = results[, "X"], col = Xcol, lwd = 2)
lines(x = results[, "time"], y = results[, "T"], col = Tcol, lwd = 2)
lines(x = results[, "time"], y = results[, "Y"], col = Ycol, lwd = 2)
#lines(x = results[, "time"], y = results[, "V"], col = 'black', lwd = 2)
#lines(x = results[, "time"], y = results[, "N"], col = 'grey', lwd = 2)
legend('topright', legend = c('Tick, Uninfected (S)', 'Tick, Infected (X)', 'Host Uninfected (T)', 'Host Infected (Y)','Tick pop', 'Host pop'), col = c(Scol, Xcol, Tcol, Ycol, 'black', 'grey'),
       lwd = 2,cex = 0.9)

```

```{r DONT USEno host mortality, changed T to H for susceptible host}
host.tick <- function(t, x, params) {
  T = x[1]
  X = x[2]
  
  H = x[3]
  Y = x[4]
  
  V = x[5] # total tick pop
  N = x[6] # total host pop
  
  beta = params[1]
  b = params[2]
  K = params[3]
  M = params[4]
  b = params[5]
  d = params[6]
  A_hat = params[7]
  A = params[8]
  v = params[9]
  
  # tick equations
  dTdt = (b*V) - (b*((T*V)/(M*N))) - (A*((T*Y)/N)) - (d*T) # susceptible
  dXdt = (A*((T*Y)/N)) - (b*((X*V)/M*N)) - (d*X) # infected
  
  # host equations
  dHdt = (beta*N) - (beta*((H*N)/K)) - (A_hat*((H*X)/N)) + (v*Y) # susceptible
  dYdt = (A_hat*((H*X)/N)) - (beta*((Y*N)/K)) - (v*Y) # infected
  
  # population equations
  dVdt = (dTdt + dXdt) # tick pop
  dNdt = (dHdt + dYdt) # host pop
  
  return(list(c(dTdt, dXdt, dHdt, dYdt, dVdt, dNdt)))
}
# tick
#V = S + X
T0 = 175 # susceptible tick
X0 = 25 # infected tick
V = T0 + X0 # tick pop v = s + x


# host
H0 = 99 # susceptible host
Y0 = 1 # infected host
N = H0 + Y0 # host pop n = t + y

initial_values = c(T = T0, X = X0, V = V,
                   H = H0, Y = Y0, N = N)


# decent params, .2, .9, 300, 3000, .01, .01, .2, .7, .9
# .2, .75, 1200, 100, .01, .001, .005, .05, .51 for 1000, 125 and 1000 114
  beta = 0 # growth rate host
  b = .02 # growth rate ticks
  
  K = 12 # carrying capacity for hosts per m^2
  M = 15 # max number of ticks per host # OG 200
  
  b = 0 # natural mortality host
  d = 0.1 # natural mortality ticks # OG .01 
  
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.4 # transmission rate from host to ticks # OG .07
  v = 0.9 # host recovery rate
  
parameters = c(beta, b, K, M, b, d, A_hat, A, v)

times = seq(0, 60, length.out = 10000)

results = lsoda(initial_values, times, host.tick, parameters)
head(results)
tail(results)
# make into data frame to analyze
model.output <- as.data.frame(ode(y = initial_values, times = times, fun = host.tick, parms = parameters))
str(model.output)

Tcol = 'red'
Xcol = 'red'
Hcol = 'royalblue3'
Ycol = 'royalblue3'

plot(x = results[, "time"], y = results[, "T"], type = 'l', col=Tcol, las = 1, lwd=2, xlab = 'Time (days)', ylab = 'Number of Individuals', ylim = c(0,200), lty = 3,
     xlim = c(0,60),main = "Host - Tick Metapopulation Model") # susceptible tick
lines(x = results[, "time"], y = results[, "X"], col = Xcol, lwd = 2,lty = 1) # infected tick
lines(x = results[, "time"], y = results[, "H"], col = Hcol, lwd = 2,lty = 3) # susceptible host
lines(x = results[, "time"], y = results[, "Y"], col = Ycol, lwd = 2,lty = 1) # infected 
#lines(x = results[, "time"], y = results[, "V"], col = 'black', lwd = 2) # tick
#lines(x = results[, "time"], y = results[, "N"], col = 'grey', lwd = 2) # host
legend('topright', legend = c('Tick, Uninfected (T)', 'Tick, Infected (X)', 'Host Uninfected (H)', 'Host Infected (Y)','Tick pop (V)', 'Host pop (N)'), col = c(Tcol, Xcol, Hcol, Ycol, 'black', 'grey'),
        lty = c(3,1,3,1), lwd = 2, cex = 0.9)

min(results[,])
```

```{r DONT USEanalyzing model output with no host growth rates}

##### Max number of ticks infected at one time? ####
## 198.9268
max(model.output$X)

#### What proportion of the population of ticks been infected over time? ####

# V = T + X
# V - T = X
  # proportion of ticks infected (X/V) 
    ## .125 or 12.5%
      model.output$X[length(time)]/ V

# N = H + Y
# N - H = Y
  # proportion of hosts infected (Y/N) 
    ## 0.01 or 1%
      model.output$Y[length(time)]/ N 

### Plot number of infected
  par(mfrow = c(2,1), mar = c(4,5,2,2))
  ## Ticks
    plot(x = model.output$time, y = (model.output$X/model.output$V ), type = 'l', las = 1, col = 'red', 
         ylab = 'Number of Infected',
         xlab = 'Time (days)',
         lwd = 2,
         cex.axis = .7, cex.lab = .8,
         main = 'Ticks',
         font.main = 2)
   ## Hosts
    plot(x = model.output$time, y = (model.output$Y/model.output$N ), type = 'l', las = 1, 
         ylab = 'Number of Infected',
         xlab = 'Time (days)',
         col = 'red',
         lwd = 2,
         cex.axis= .7, cex.lab = .8,
         main = 'Hosts', font.main = 2)
par(mfrow = c(1,1))    
#### When was the rate of transmission highest? ####

# rate of transmission = dY/dt
# dY/dt = A*(T*Y/N) - d*T

NewInfec <- A*((model.output$H)*(model.output$X)) # need to double check this
plot(x = model.output$time, y = NewInfec, lwd = 1, type = 'l',
     las = 1, 
     ylab = 'New Infections',
     xlab = 'Time (days)',
     main = 'Max New Host Infections',
     col = 'red')
max.NewInfec <- max(NewInfec)

for(i in 1:length(time)) {
  if(NewInfec[i] == max.NewInfec){
    T.maxnewinf <- tset[i]
  }
}
T.maxnewinf
abline(v = T.maxnewinf, lty = 2)

#### What happens to R0 as Infectiousness (beta) increases? ####
A_set <- seq(.1, .9, length.out = 1000)

R0_set <- A_set*N/v

plot(x = A_set, y = R0_set, type = 'l',
     xlab = 'Host Population Size (N)',
     ylab = 'Reproductive Number (R0)',
     main = 'Change in Infectiousness (A)')

#### What happens to R0 as N (host population) increases? ####
N_set <- seq(1, 100, length.out = 1000)

R0_set <- A*N_set/v

plot(x = N_set, y = R0_set, type = 'l',
     xlab = 'Host Population Size (N)',
     ylab = 'Reproductive Number (R0)',
     main = 'Change in Host Population Size (N)')


### What happens to R0 as host recovery rate increases? ###
v_set <- seq(.001, .1, length.out = 1000)

R0_set <- A*N/v_set

plot(x = v_set, y = R0_set, type = 'l',
     xlab = 'Host Recovery Rate (gamma)',
     ylab = 'Reproductive Number (R0)',
     main = 'Change in Recovery rate (v)')
```

```{r}
final.model <- function(t, x, params) {
  T = x[1]
  X = x[2]
  H = x[3]
  Y = x[4]
  
  
  b = params[1] # birth rate ticks
  M = params[2] # carrying capacity of ticks per host
  d = params[3] # death rate of ticks
  A_hat = params[4] # transmission from tick to host
  A = params[5] # transmission from host to tick
  g = params[6] # recovery of host
  v = params[7] #vertical transmision
  
  # tick equations 
  dTdt = (1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T) # susceptible
  dXdt = v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X) # infected
  
  # host equations
  dHdt =  - (A_hat*H*X)/(H + Y) + (g*Y) # susceptible
  dYdt = (A_hat*H*X)/(H + Y) - (g*Y) # infected
  
  
  return(list(c(dTdt, dXdt, dHdt, dYdt)))
}
# tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

initial_values = c(T = T0, X = X0, H = H0, Y = Y0)


  b = .09 # birth rate ticks
  M = 200 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.5 # transmission rate from host to ticks # OG .07
  g = 0.03 # host recovery rate
  v = .05 # vertical transmisison
  
parameters = c(b, M, d, A_hat, A, g, v)

times = seq(0, 6000, length.out = 10000)

results = lsoda(initial_values, times, final.model, parameters)
head(results)
tail(results)

# make into data frame to analyze
final.model.output <- as.data.frame(ode(y = initial_values, times = times, fun = final.model, parms = parameters))
str(final.model.output)

Tcol = 'red'
Xcol = 'red'
Hcol = 'royalblue3'
Ycol = 'royalblue3'

plot(x = results[, "time"], y = results[, "T"], type = 'l', col=Tcol, las = 1, lwd=2, xlab = 'Time (days)', ylab = 'Number of Individuals', ylim = c(0,200), lty = 3,
     xlim = c(0,6000),main = "Host - Tick - Pathogen Population Model") # susceptible tick
lines(x = results[, "time"], y = results[, "X"], col = Xcol, lwd = 2,lty = 1) # infected tick
lines(x = results[, "time"], y = results[, "H"], col = Hcol, lwd = 2,lty = 3) # susceptible host
lines(x = results[, "time"], y = results[, "Y"], col = Ycol, lwd = 2,lty = 1) # infected 
legend('topright', legend = c('Tick, Uninfected (T)', 'Tick, Infected (X)', 'Host, Uninfected (H)', 'Host, Infected (Y)'), col = c(Tcol, Xcol, Hcol, Ycol),
        lty = c(3,1,3,1), lwd = 2, cex = 0.9)
min(results[,])
```



```{r THIS ONE IS FINAL final.model and final.model.output changed equations no:V, N, b, beta, Not density dependent for hosts}
final.model <- function(t, x, params) {
  T = x[1]
  X = x[2]
  H = x[3]
  Y = x[4]
  
  
  b = params[1] # birth rate ticks
  M = params[2] # carrying capacity of ticks per host
  d = params[3] # death rate of ticks
  A_hat = params[4] # transmission from tick to host
  A = params[5] # transmission from host to tick
  g = params[6] # recovery of host
  v = params[7] #vertical transmision
  
  # tick equations
  dTdt = (((1-v)*b*X + b*T)/(M*(H+Y))) - (A*T*Y)/(H+Y) - d*T
  dXdt = ((v*b*X)/(M*(H+Y))) + A*T*Y/(H+Y) - d*X
  # host equations
  dHdt =  - (A_hat*H*X)/(H + Y) + (g*Y) # susceptible
  dYdt = (A_hat*H*X)/(H + Y) - (g*Y) # infected
  
  
  return(list(c(dTdt, dXdt, dHdt, dYdt)))
}
# tick
#V = T + X
T0 = 1 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 1 # susceptible host
Y0 = 1 # infected host

initial_values = c(T = T0, X = X0, H = H0, Y = Y0)


  b = .9 # birth rate ticks
  M = 1500 # max number of ticks per host # OG 200
  d = 0.001 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.9 # transmission rate from host to ticks # OG .07
  g = 0.3 # host recovery rate
  v = .5 # vertical transmisison
  
parameters = c(b, M, d, A_hat, A, g, v)

times = seq(0, 20000, length.out = 10000)

results = lsoda(initial_values, times, final.model, parameters)
head(results)
tail(results)

# make into data frame to analyze
final.model.output <- as.data.frame(ode(y = initial_values, times = times, fun = final.model, parms = parameters))
str(final.model.output)

Tcol = 'red'
Xcol = 'red'
Hcol = 'royalblue3'
Ycol = 'royalblue3'

plot(x = results[, "time"], y = results[, "T"], type = 'l', col=Tcol, las = 1, lwd=2, xlab = 'Time (days)', ylab = 'Number of Individuals', ylim = c(0,2), lty = 3,
     xlim = c(0,20000),main = "Host - Tick - Pathogen Population Model") # susceptible tick
lines(x = results[, "time"], y = results[, "X"], col = Xcol, lwd = 2,lty = 1) # infected tick
lines(x = results[, "time"], y = results[, "H"], col = Hcol, lwd = 2,lty = 3) # susceptible host
lines(x = results[, "time"], y = results[, "Y"], col = Ycol, lwd = 2,lty = 1) # infected 
 legend(x = 13000, y = 1, legend = c('Tick, Uninfected (T)', 'Tick, Infected (X)', 'Host, Uninfected (H)', 'Host, Infected (Y)'), col = c(Tcol, Xcol, Hcol, Ycol),
        lty = c(3,1,3,1), lwd = 2, cex = 0.9)
min(results[,])


final.model.output[length(tset),'T']
final.model.output[length(tset),'X']
final.model.output[length(tset),'H']
final.model.output[length(tset),'Y']
```

```{r analyze final.model.output R0, proportion}
##### Max number of ticks infected at one time? ####
## 198.9268
max(final.model.output$X)

#### What proportion of the population of ticks been infected over time? ####

# V = T + X
# V - T = X
  # proportion of ticks infected (X/V) 
    ## .125 or 12.5%
     final.model.output$X[length(time)]/ (T + X)

# N = H + Y
# N - H = Y
  # proportion of hosts infected (Y/N) 
    ## 0.01 or 1%
      final.model.output$Y[length(time)]/ (H + Y) 
### Plot number of infected
  par(mfrow = c(2,1), mar = c(4,5,2,2))
  ## Ticks
    plot(x = final.model$time, y = (final.model$X/(final.model$T +  final.model$X)), type = 'l', las = 1, col = 'red', 
         ylab = 'Number of Infected',
         xlab = 'Time (days)',
         lwd = 2,
         cex.axis = .7, cex.lab = .8,
         main = 'Ticks',
         font.main = 2)
   ## Hosts
    plot(x = final.model$time, y = (final.model$Y/(final.model$H + final.model$Y)), type = 'l', las = 1, 
         ylab = 'Number of Infected',
         xlab = 'Time (days)',
         col = 'red',
         lwd = 2,
         cex.axis= .7, cex.lab = .8,
         main = 'Hosts', font.main = 2)
par(mfrow = c(1,1))    
#### When was the rate of transmission highest? ####

# rate of transmission = dY/dt
# dY/dt = A*(T*Y/N) - d*T

NewInfec <- A*((final.model.output$H)*(final.model.output$X)) # need to double check this
plot(x = final.model.output$time, y = NewInfec, lwd = 1, type = 'l',
     las = 1, 
     ylab = 'New Infections',
     xlab = 'Time (days)',
     main = 'Max New Host Infections',
     col = 'red')
max.NewInfec <- max(NewInfec)

for(i in 1:length(time)) {
  if(NewInfec[i] == max.NewInfec){
    T.maxnewinf <- tset[i]
  }
}
T.maxnewinf
abline(v = T.maxnewinf, lty = 2)

#### What happens to R0 as Infectiousness (beta) increases? ####
A_set <- seq(.1, .9, length.out = 1000)

R0_set <- A_set*((T + Y)/(H+Y))/g

plot(x = A_set, y = R0_set, type = 'l',
     xlab = 'Host Population Size (N)',
     ylab = 'Reproductive Number (R0)',
     main = 'Change in Infectiousness (A)')

#### What happens to R0 as N (host population) increases? ####
N_set <- seq(1, 100, length.out = 1000)

R0_set <- A*N_set/g

plot(x = N_set, y = R0_set, type = 'l',
     xlab = 'Host Population Size (N)',
     ylab = 'Reproductive Number (R0)',
     main = 'Change in Host Population Size (N)')


### What happens to R0 as host recovery rate increases? ###
g_set <- seq(.001, .1, length.out = 1000)

R0_set <- A*N/g_set

plot(x = g_set, y = R0_set, type = 'l',
     xlab = 'Host Recovery Rate (gamma)',
     ylab = 'Reproductive Number (R0)',
     main = 'Change in Recovery rate (v)')
```



```{r simulations for final.model GENERAL change A}
##########################
# A = 0.01, gamma = .1
#########################


  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.4 # transmission rate from ticks to hosts #OG .02
  A = 0.01 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu1<- NaN*tset; T.simu1[1] <-T0
X.simu1<- NaN*tset; X.simu1[1] <-X0
H.simu1<- NaN*tset; H.simu1[1] <-H0
Y.simu1<- NaN*tset; Y.simu1[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu1[i-1]
  X <- X.simu1[i-1]
  H <- H.simu1[i-1]
  Y <- Y.simu1[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu1[i] <- T + dT
  X.simu1[i] <- X + dX
  H.simu1[i] <- H + dH
  Y.simu1[i] <- Y + dY
}

plot(x = tset, y = X.simu1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected',
     main = 'A_hat = 0.01, gamma = 0.1')





##########################
# A = 0.1, gamma = .1
#########################


  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.4 # transmission rate from ticks to hosts #OG .02
  A = 0.1 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu2<- NaN*tset; T.simu2[1] <-T0
X.simu2<- NaN*tset; X.simu2[1] <-X0
H.simu2<- NaN*tset; H.simu2[1] <-H0
Y.simu2<- NaN*tset; Y.simu2[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu2[i-1]
  X <- X.simu2[i-1]
  H <- H.simu2[i-1]
  Y <- Y.simu2[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu2[i] <- T + dT
  X.simu2[i] <- X + dX
  H.simu2[i] <- H + dH
  Y.simu2[i] <- Y + dY
}

plot(x = tset, y = X.simu2, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected',
     main = 'A_hat = 0.2, gamma = 0.1')



##########################
# A = 0.9, gamma = .1
#########################


  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.4 # transmission rate from ticks to hosts #OG .02
  A = 0.9 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu3<- NaN*tset; T.simu3[1] <-T0
X.simu3<- NaN*tset; X.simu3[1] <-X0
H.simu3<- NaN*tset; H.simu3[1] <-H0
Y.simu3<- NaN*tset; Y.simu3[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu3[i-1]
  X <- X.simu3[i-1]
  H <- H.simu3[i-1]
  Y <- Y.simu3[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu3[i] <- T + dT
  X.simu3[i] <- X + dX
  H.simu3[i] <- H + dH
  Y.simu3[i] <- Y + dY
}

plot(x = tset, y = X.simu3, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected',
     main = 'A_hat = 0.9, gamma = 0.1')


### Plot all 3
plot(x = tset, y = X.simu3, type = 'l', las = 1, lwd = 3,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'Changing transmission rate from host to tick', col = 'red')
lines(x = tset, y = X.simu2, col = 'red', lwd = 2)
lines(x = tset, y = X.simu1, col = 'red', lwd = 1)
legend(x = 'topright', legend = c('A = 0.01','A = 0.1','A = 0.9'),
       col = 'red', lwd = c(1,2,3))

```

Question 1: Does host competency matter for bm and bb?
```{r Q1 BM N is constant, change competency A for each host}

#########################
# PERO : N = 50; A = .9
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.9 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bm.pero1<- NaN*tset; T.simu.bm.pero1[1] <-T0
X.simu.bm.pero1<- NaN*tset; X.simu.bm.pero1[1] <-X0
H.simu.bm.pero1<- NaN*tset; H.simu.bm.pero1[1] <-H0
Y.simu.bm.pero1<- NaN*tset; Y.simu.bm.pero1[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bm.pero1[i-1]
  X <- X.simu.bm.pero1[i-1]
  H <- H.simu.bm.pero1[i-1]
  Y <- Y.simu.bm.pero1[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bm.pero1[i] <- T + dT
  X.simu.bm.pero1[i] <- X + dX
  H.simu.bm.pero1[i] <- H + dH
  Y.simu.bm.pero1[i] <- Y + dY
}

plot(x = tset, y = X.simu.bm.pero1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected TICKS',
     main = 'BM: PERO A = .9, N = 50')


#########################
# NEFU : N = 50; A = .3
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.3 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bm.nefu1<- NaN*tset; T.simu.bm.nefu1[1] <-T0
X.simu.bm.nefu1<- NaN*tset; X.simu.bm.nefu1[1] <-X0
H.simu.bm.nefu1<- NaN*tset; H.simu.bm.nefu1[1] <-H0
Y.simu.bm.nefu1<- NaN*tset; Y.simu.bm.nefu1[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bm.nefu1[i-1]
  X <- X.simu.bm.nefu1[i-1]
  H <- H.simu.bm.nefu1[i-1]
  Y <- Y.simu.bm.nefu1[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bm.nefu1[i] <- T + dT
  X.simu.bm.nefu1[i] <- X + dX
  H.simu.bm.nefu1[i] <- H + dH
  Y.simu.bm.nefu1[i] <- Y + dY
}

plot(x = tset, y = X.simu.bm.nefu1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'BM: NEFU A = .3, N = 50')


#########################
# SCOC : N = 50; A = .5
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.5 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bm.scoc1<- NaN*tset; T.simu.bm.scoc1[1] <-T0
X.simu.bm.scoc1<- NaN*tset; X.simu.bm.scoc1[1] <-X0
H.simu.bm.scoc1<- NaN*tset; H.simu.bm.scoc1[1] <-H0
Y.simu.bm.scoc1<- NaN*tset; Y.simu.bm.scoc1[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bm.scoc1[i-1]
  X <- X.simu.bm.scoc1[i-1]
  H <- H.simu.bm.scoc1[i-1]
  Y <- Y.simu.bm.scoc1[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bm.scoc1[i] <- T + dT
  X.simu.bm.scoc1[i] <- X + dX
  H.simu.bm.scoc1[i] <- H + dH
  Y.simu.bm.scoc1[i] <- Y + dY
}

plot(x = tset, y = X.simu.bm.scoc1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'BM: SCOC A = .5, N = 35')


### PLOT ALL 3 species
plot(x = tset, y = X.simu.bm.pero1, type = 'l', las = 1, lwd = 3,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'Number of BM Infected Ticks by Host Blood Meal (N = 50)',
     col = 'maroon')
lines(x = tset, y = X.simu.bm.scoc1, lwd = 2, col = 'maroon')
lines(x = tset, y = X.simu.bm.nefu1, lwd = 1,col = 'maroon')
legend('topright', legend = c('PERO: A = .9', 'NEFU: A = .3', 'SCOC: A = .5'), lwd = c(3,2,1),
       col = 'maroon')

```

```{r Q1 BB N is constant, changing competency A for each host }

#########################
# PERO : N = 50; A = .6
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.6 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bb.pero1<- NaN*tset; T.simu.bb.pero1[1] <-T0
X.simu.bb.pero1<- NaN*tset; X.simu.bb.pero1[1] <-X0
H.simu.bb.pero1<- NaN*tset; H.simu.bb.pero1[1] <-H0
Y.simu.bb.pero1<- NaN*tset; Y.simu.bb.pero1[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bb.pero1[i-1]
  X <- X.simu.bb.pero1[i-1]
  H <- H.simu.bb.pero1[i-1]
  Y <- Y.simu.bb.pero1[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bb.pero1[i] <- T + dT
  X.simu.bb.pero1[i] <- X + dX
  H.simu.bb.pero1[i] <- H + dH
  Y.simu.bb.pero1[i] <- Y + dY
}

plot(x = tset, y = X.simu.bb.pero1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected TICKS',
     main = 'BB: PERO A = .6, N = 50')


#########################
# NEFU : N = 50; A = .9
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.9 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bb.nefu1<- NaN*tset; T.simu.bb.nefu1[1] <-T0
X.simu.bb.nefu1<- NaN*tset; X.simu.bb.nefu1[1] <-X0
H.simu.bb.nefu1<- NaN*tset; H.simu.bb.nefu1[1] <-H0
Y.simu.bb.nefu1<- NaN*tset; Y.simu.bb.nefu1[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bb.nefu1[i-1]
  X <- X.simu.bb.nefu1[i-1]
  H <- H.simu.bb.nefu1[i-1]
  Y <- Y.simu.bb.nefu1[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bb.nefu1[i] <- T + dT
  X.simu.bb.nefu1[i] <- X + dX
  H.simu.bb.nefu1[i] <- H + dH
  Y.simu.bb.nefu1[i] <- Y + dY
}

plot(x = tset, y = X.simu.bb.nefu1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'BB: NEFU A = .9, N = 50')


#########################
# SCOC : N = 50; A = .001
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.001 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 49 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bb.scoc1<- NaN*tset; T.simu.bb.scoc1[1] <-T0
X.simu.bb.scoc1<- NaN*tset; X.simu.bb.scoc1[1] <-X0
H.simu.bb.scoc1<- NaN*tset; H.simu.bb.scoc1[1] <-H0
Y.simu.bb.scoc1<- NaN*tset; Y.simu.bb.scoc1[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bb.scoc1[i-1]
  X <- X.simu.bb.scoc1[i-1]
  H <- H.simu.bb.scoc1[i-1]
  Y <- Y.simu.bb.scoc1[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bb.scoc1[i] <- T + dT
  X.simu.bb.scoc1[i] <- X + dX
  H.simu.bb.scoc1[i] <- H + dH
  Y.simu.bb.scoc1[i] <- Y + dY
}

plot(x = tset, y = X.simu.bb.scoc1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'BM: SCOC A = .001, N = 50')


### PLOT ALL 3 species
plot(x = tset, y = X.simu.bb.pero1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'Number of BM Infected Ticks by Host Blood Meal (N = 50)',
     col = 'royalblue',
     ylim = c(0, 120))
lines(x = tset, y = X.simu.bb.scoc1, lwd = 1, col = 'royalblue')
lines(x = tset, y = X.simu.bb.nefu1, lwd = 3,col = 'royalblue')
legend('topright', legend = c('NEFU: A = .9','PERO: A = .6', 'SCOC: A = .001'), lwd = c(3,2,1),
       col = 'royalblue')

```

Question 1 ANSWER
```{r Q1 COMPARING host competency for BM and BB with densities equal}
#par(mfrow = c(1,1))

#BM
plot(x = tset, y = X.simu.bm.pero1, type = 'l', las = 1, lwd = 3,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'Number of Infected Ticks by Host Competency (N = 50)',
     col = 'maroon', lty = 1)
lines(x = tset, y = X.simu.bm.scoc1, lwd = 2, col = 'maroon')
lines(x = tset, y = X.simu.bm.nefu1, lwd = 1,col = 'maroon')
#legend('topright', legend = c('PERO: A = .9', 'NEFU: A = .3', 'SCOC: A = .5'), lwd = c(3,2,1),col = 'maroon')
# BB
lines(x = tset, y = X.simu.bb.pero1, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'Number of BB Infected Ticks by Host Blood Meal (N = 50)',
     col = 'royalblue',
     ylim = c(0, 120))
lines(x = tset, y = X.simu.bb.scoc1, lwd = 1, col = 'royalblue')
lines(x = tset, y = X.simu.bb.nefu1, lwd = 3,col = 'royalblue', lty = 3)
#legend('topright', legend = c('NEFU: A = .9','PERO: A = .6', 'SCOC: A = .001'), lwd = c(3,2,1),col = 'royalblue')
legend('topright', legend = c('BM', 'BB','High', 'Medium', 'Low'),
       col = c('maroon', 'royalblue', 'black','black','black'),
       lwd = c(3,3,3,2,1))




#### Analyzing Q1 ###
## Calculating the max infected ticks for bb
bb_nefu1<-max(X.simu.bb.nefu1)
bb_pero1<-max(X.simu.bb.pero1)
bb_scoc1<-max(X.simu.bb.scoc1)

bb_max1 <- bb_nefu1 + bb_pero1 + bb_scoc1

## Calculating the sum infected ticks for bb
bb_nefu1<-sum(X.simu.bb.nefu1)
bb_pero1<-sum(X.simu.bb.pero1)
bb_scoc1<-sum(X.simu.bb.scoc1)

bb_sum1 <- bb_nefu1 + bb_pero1 + bb_scoc1


## Calculating the max infected ticks for bm
bm_nefu1<-max(X.simu.bm.nefu1)
bm_pero1<-max(X.simu.bm.pero1)
bm_scoc1<-max(X.simu.bm.scoc1)

bm_max1 <- bm_nefu1 + bm_pero1 + bm_scoc1
## Calculating the max infected ticks for bm
bm_nefu1<-sum(X.simu.bm.nefu1)
bm_pero1<-sum(X.simu.bm.pero1)
bm_scoc1<-sum(X.simu.bm.scoc1)

bm_sum1 <- bm_nefu1 + bm_pero1 + bm_scoc1

```


Question 2: or is host density more important?

```{r Q2 BM actual host numbers and competency}

#########################
# PERO : N = 26; A = .9
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.9 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 25 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bm.pero2<- NaN*tset; T.simu.bm.pero2[1] <-T0
X.simu.bm.pero2<- NaN*tset; X.simu.bm.pero2[1] <-X0
H.simu.bm.pero2<- NaN*tset; H.simu.bm.pero2[1] <-H0
Y.simu.bm.pero2<- NaN*tset; Y.simu.bm.pero2[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bm.pero2[i-1]
  X <- X.simu.bm.pero2[i-1]
  H <- H.simu.bm.pero2[i-1]
  Y <- Y.simu.bm.pero2[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bm.pero2[i] <- T + dT
  X.simu.bm.pero2[i] <- X + dX
  H.simu.bm.pero2[i] <- H + dH
  Y.simu.bm.pero2[i] <- Y + dY
}

plot(x = tset, y = X.simu.bm.pero2, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected TICKS',
     main = 'BM: PERO A = .9, N = 26')


#########################
# NEFU : N = 20; A = .3
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.3 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 19 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bm.nefu2<- NaN*tset; T.simu.bm.nefu2[1] <-T0
X.simu.bm.nefu2<- NaN*tset; X.simu.bm.nefu2[1] <-X0
H.simu.bm.nefu2<- NaN*tset; H.simu.bm.nefu2[1] <-H0
Y.simu.bm.nefu2<- NaN*tset; Y.simu.bm.nefu2[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bm.nefu2[i-1]
  X <- X.simu.bm.nefu2[i-1]
  H <- H.simu.bm.nefu2[i-1]
  Y <- Y.simu.bm.nefu2[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bm.nefu2[i] <- T + dT
  X.simu.bm.nefu2[i] <- X + dX
  H.simu.bm.nefu2[i] <- H + dH
  Y.simu.bm.nefu2[i] <- Y + dY
}

plot(x = tset, y = X.simu.bm.nefu2, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'BM: NEFU A = .3, N = 20')


#########################
# SCOC : N = 35; A = .5
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.5 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 34 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bm.scoc2<- NaN*tset; T.simu.bm.scoc2[1] <-T0
X.simu.bm.scoc2<- NaN*tset; X.simu.bm.scoc2[1] <-X0
H.simu.bm.scoc2<- NaN*tset; H.simu.bm.scoc2[1] <-H0
Y.simu.bm.scoc2<- NaN*tset; Y.simu.bm.scoc2[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bm.scoc2[i-1]
  X <- X.simu.bm.scoc2[i-1]
  H <- H.simu.bm.scoc2[i-1]
  Y <- Y.simu.bm.scoc2[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bm.scoc2[i] <- T + dT
  X.simu.bm.scoc2[i] <- X + dX
  H.simu.bm.scoc2[i] <- H + dH
  Y.simu.bm.scoc2[i] <- Y + dY
}

plot(x = tset, y = X.simu.bm.scoc2, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'BM: SCOC A = .5, N = 35')


### PLOT ALL 3 species
plot(x = tset, y = X.simu.bm.pero2, type = 'l', las = 1, lwd = 3,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'Number of Infected BM Ticks by Host Blood Meal',
     col = 'maroon')
lines(x = tset, y = X.simu.bm.scoc2, lwd = 2, col = 'maroon')
lines(x = tset, y = X.simu.bm.nefu2, lwd = 1,col = 'maroon')
legend('topright', legend = c('PERO: N = 26, A = 0.9','SCOC: N = 35, A = 0.5', 'NEFU: N = 20, A = 0.3'), lwd = c(3,2,1),
       col = 'maroon')
```

```{r Q2 BB actual host numbers and competency}

#########################
# PERO : N = 26; A = .6
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.6 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 25 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bb.pero2<- NaN*tset; T.simu.bb.pero2[1] <-T0
X.simu.bb.pero2<- NaN*tset; X.simu.bb.pero2[1] <-X0
H.simu.bb.pero2<- NaN*tset; H.simu.bb.pero2[1] <-H0
Y.simu.bb.pero2<- NaN*tset; Y.simu.bb.pero2[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bb.pero2[i-1]
  X <- X.simu.bb.pero2[i-1]
  H <- H.simu.bb.pero2[i-1]
  Y <- Y.simu.bb.pero2[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bb.pero2[i] <- T + dT
  X.simu.bb.pero2[i] <- X + dX
  H.simu.bb.pero2[i] <- H + dH
  Y.simu.bb.pero2[i] <- Y + dY
}

plot(x = tset, y = X.simu.bb.pero2, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected TICKS',
     main = 'BB: PERO A = .6, N = 26')


#########################
# NEFU : N = 20; A = .9
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.9 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 19 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bb.nefu2<- NaN*tset; T.simu.bb.nefu2[1] <-T0
X.simu.bb.nefu2<- NaN*tset; X.simu.bb.nefu2[1] <-X0
H.simu.bb.nefu2<- NaN*tset; H.simu.bb.nefu2[1] <-H0
Y.simu.bb.nefu2<- NaN*tset; Y.simu.bb.nefu2[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bb.nefu2[i-1]
  X <- X.simu.bb.nefu2[i-1]
  H <- H.simu.bb.nefu2[i-1]
  Y <- Y.simu.bb.nefu2[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bb.nefu2[i] <- T + dT
  X.simu.bb.nefu2[i] <- X + dX
  H.simu.bb.nefu2[i] <- H + dH
  Y.simu.bb.nefu2[i] <- Y + dY
}

plot(x = tset, y = X.simu.bb.nefu2, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'BB: NEFU A = .9, N = 20')


#########################
# SCOC : N = 35; A = .001
#########################
  b = .01 # birth rate ticks
  M = 100 # max number of ticks per host # OG 200
  d = 0.09 # natural mortality ticks # OG .01 
  A_hat = 0.9 # transmission rate from ticks to hosts #OG .02
  A = 0.001 # transmission rate from host to ticks # OG .07
  g = 0.1 # host recovery rate
  v = .5 # vertical transmisison

 # tick
#V = T + X
T0 = 199 # susceptible tick
X0 = 1 # infected tick


# host
# N = H + Y
H0 = 34 # susceptible host
Y0 = 1 # infected host

tset<- seq(0, 60, length.out = 10000)
T.simu.bb.scoc2<- NaN*tset; T.simu.bb.scoc2[1] <-T0
X.simu.bb.scoc2<- NaN*tset; X.simu.bb.scoc2[1] <-X0
H.simu.bb.scoc2<- NaN*tset; H.simu.bb.scoc2[1] <-H0
Y.simu.bb.scoc2<- NaN*tset; Y.simu.bb.scoc2[1] <-Y0

for(i in 2:length(tset)) {
  dt <- tset[i] - tset[i-1]
  T <- T.simu.bb.scoc2[i-1]
  X <- X.simu.bb.scoc2[i-1]
  H <- H.simu.bb.scoc2[i-1]
  Y <- Y.simu.bb.scoc2[i-1]
  
  dT = ((1-v)*(b*(T+X)) - (b*T)/(M*(H+Y)) - (A*(T*Y)/(H+Y)) - (d*T))*dt # susceptible
  dX = (v*b*X + (A*(T*Y)/(H+Y)) - (b*X)/(M*(H+Y)) - (d*X))*dt # infected
  
  # host equations
  dH =  (- (A_hat*H*X)/(H + Y) + (g*Y))*dt # susceptible
  dY = ((A_hat*H*X)/(H + Y) - (g*Y))*dt # infected
  
  
  T.simu.bb.scoc2[i] <- T + dT
  X.simu.bb.scoc2[i] <- X + dX
  H.simu.bb.scoc2[i] <- H + dH
  Y.simu.bb.scoc2[i] <- Y + dY
}

plot(x = tset, y = X.simu.bb.scoc2, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'BM: SCOC A = .001, N = 35')


### PLOT ALL 3 species
plot(x = tset, y = X.simu.bb.pero2, type = 'l', las = 1, lwd = 2,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'Number of BM Infected Ticks by Host Blood Meal',
     col = 'royalblue',
     ylim = c(0, 130))
lines(x = tset, y = X.simu.bb.scoc2, lwd = 1, col = 'royalblue')
lines(x = tset, y = X.simu.bb.nefu2, lwd = 3,col = 'royalblue')
legend('topright', legend = c('NEFU: N = 20, A = .9','PERO: N = 26, A = .6', 'SCOC: N = 35, A = .001'), lwd = c(3,2,1),
       col = 'royalblue')
```



Question 2 ANSWER
```{r COMPARING BM and BB with actual numbers and competency}
# BM
plot(x = tset, y = X.simu.bm.pero2, type = 'l', las = 1, lwd = 3,
     xlab = 'Time', ylab = 'Number of Infected Ticks',
     main = 'Number of Infeced Ticks by Host Blood Meal',
     col = 'maroon',
     ylim = c(0,130))
lines(x = tset, y = X.simu.bm.scoc2, lwd = 2, col = 'maroon')
lines(x = tset, y = X.simu.bm.nefu2, lwd = 1,col = 'maroon')
#legend('topright', legend = c('PERO: N = 26, A = 0.9','SCOC: N = 35, A = 0.5', 'NEFU: N = 20, A = 0.3'), lwd = c(3,2,1),col = 'maroon')
# BB
lines(x = tset, y = X.simu.bb.pero2, type = 'l', las = 1, lwd = 2, col = 'royalblue')
lines(x = tset, y = X.simu.bb.scoc2, lwd = 1, col = 'royalblue')
lines(x = tset, y = X.simu.bb.nefu2, lwd = 3,col = 'royalblue')
#legend('topright', legend = c('NEFU: N = 20, A = .9','PERO: N = 26, A = .6', 'SCOC: N = 35, A = .001'), lwd = c(3,2,1),col = 'royalblue')
legend('topright', legend = c('BM', 'BB','High', 'Medium', 'Low'),
       col = c('maroon', 'royalblue', 'black','black','black'),
       lwd = c(3,3,3,2,1))


#### Analyzing Q2 ###
## Calculating the max infected ticks for bb
bb_nefu2<-max(X.simu.bb.nefu2)
bb_pero2<-max(X.simu.bb.pero2)
bb_scoc2<-max(X.simu.bb.scoc2)

bb_max2 <- bb_nefu2 + bb_pero2 + bb_scoc2

## Calculating the sum infected ticks for bb
bb_nefu2<-sum(X.simu.bb.nefu2)
bb_pero2<-sum(X.simu.bb.pero2)
bb_scoc2<-sum(X.simu.bb.scoc2)

bb_sum2 <- bb_nefu2 + bb_pero2 + bb_scoc2


## Calculating the max infected ticks for bm
bm_nefu2<-max(X.simu.bm.nefu2)
bm_pero2<-max(X.simu.bm.pero2)
bm_scoc2<-max(X.simu.bm.scoc2)

bm_max2 <- bm_nefu2 + bm_pero2 + bm_scoc2
## Calculating the max infected ticks for bm
bm_nefu2<-sum(X.simu.bm.nefu2)
bm_pero2<-sum(X.simu.bm.pero2)
bm_scoc2<-sum(X.simu.bm.scoc2)

bm_sum2 <- bm_nefu2 + bm_pero2 + bm_scoc2

```

```{r making data tables}

library(knitr)
library(ggplot2)

## Making data table
sum <- c(bm_sum1,bb_sum1,bm_sum2,bb_sum2)
max <- c(bm_max1,bb_max1,bm_max2,bb_max2)
pathogen <- c('BM', 'BB','BM', 'BB')
question <- c('1','1', '2','2')

# entire data table
analysis <- data.frame(pathogen,question, sum, max)
colnames(analysis) = c('Pathogen', 'Question', 'Sum Infected Ticks', 'Max Infected Ticks')
str(analysis)
#View(analysis)

?kable
kable(analysis, digits= 1, align = 'c',
      format.args = list(big.mark = ',', scientific = FALSE))


```

