---
title: "bifurcation diagrams"
author: "sbsambado"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

State variables
  H = rodent host (prey)
  T = tick (predator)

Parameters
r = growth rate of H
alpha = mortality associated 

```{r state variables and parameters}

r_x <- 1 		# prey X's growth rate
K_x <- 100 		# prey X's carrying capacity
a_x <- 0.03		# attack rate of predator on prey X
c <- 0.05		# predator's conversion efficiency
a_y <- 0.03		# attack rate of predator on prey Y
d_p <- 0.25		# mortality rate of predator
K_p <- 25		# predator's carrying capacity
Y <- 500		# abundance of other prey type

X0 <- 1 # prey X initial population size
P0 <- 1 # predator initial population size
```

```{r}
tset <- seq(0,100,length.out=20000)
X.simu1 <- NaN*tset
X.simu1[1] <- X0
P.simu1 <- NaN*tset
P.simu1[1] <- P0

for(i in 2:length(tset)){
	dt <- tset[i]-tset[i-1]
	X <- X.simu1[i-1]
	P <- P.simu1[i-1]
	dX <- ( r_x*X*(1-X/K_x) - a_x*P*X ) * dt
	dP <- ( P*(c*(a_x*X+a_y*Y)-d_p)*(1-P/K_p) ) * dt
	X.simu1[i] <- X.simu1[i-1] + dX
	P.simu1[i] <- P.simu1[i-1] + dP
}
```

```{r}
Xcol <- 'blue'
Pcol <- 'red'

plot(tset,X.simu1,type='l',xlab='Time',ylab='Density',las=1,lwd=2,col=Xcol)
lines(tset,P.simu1,lwd=2,col=Pcol)
legend(x = 70, y = 50, legend = c('Prey','Predator'),lwd=2,col=c(Xcol,Pcol))
```

```{r}
X0 <- X.simu1[length(tset)]
P0 <- P.simu1[length(tset)]

h_x <- 0.65 		# hunting rate of species X
h_p <- 0.325		# hunting rate of species P
```

```{r}
Yset <- seq(0,1000,length.out = 50)

plot(tset,X.simu1,type='l',xlab='Time',ylab='Density',las=1,lwd=2,col=Xcol)
lines(tset,P.simu1,lwd=2,col=Pcol)
legend(x = 70, y = 50, legend = c('Prey','Predator'),lwd = 2,col=c(Xcol,Pcol))

Xstarset <- NaN*Yset
Pstarset <- NaN*Yset

for(j in 1:length(Yset)){
	Y <- Yset[j] 
	
	X.simu <- NaN*tset # create a holding vector for the prey population X of the same length as tset (20,000)
	X.simu[1] <- 1   
	P.simu <- NaN*tset 
	P.simu[1] <- 1
	
	for(i in 2:length(tset)){
		dt <- tset[i]-tset[i-1]
		X <- X.simu[i-1]
		P <- P.simu[i-1]
		dX <- ( r_x*X*(1-X/K_x) - a_x*P*X - h_x*X ) * dt
		dP <- ( P*(c*(a_x*X+a_y*Y)-d_p)*(1-P/K_p) - h_p*P ) * dt
		X.simu[i] <- X.simu[i-1] + dX
		P.simu[i] <- P.simu[i-1] + dP	
	}
	
	Xstarset[j] <- X.simu[length(tset)]
	Pstarset[j] <- P.simu[length(tset)]
	
}

plot(Yset,Pstarset,type='l',lwd=2,col=Pcol,las=1,xlab='Density of alternate prey, Y',ylab='Stable equilibria of predator, P*')

plot(Yset,Xstarset,type='l',lwd=2,col=Xcol,las=1,xlab='Density of alternate prey, Y',ylab='Stable equilibria of focal prey, X*')
```
```{r}
h_xset <- seq(0.01,.9,length.out=50)
Xstarset <- NaN*h_xset
Pstarset <- NaN*h_xset
for(j in 1:length(h_xset)){
	h_x <- h_xset[j] 
	
	X.simu2 <- NaN*tset # create a holding vector for the prey population X of the same length as tset (20,000)
	X.simu2[1] <- 1   
	P.simu2 <- NaN*tset 
	P.simu2[1] <- 1
	
	for(i in 2:length(tset2)){
		dt <- tset2[i]-tset2[i-1]
		X <- X.simu2[i-1]
		P <- P.simu2[i-1]
		dX <- ( r_x*X*(1-X/K_x) - a_x*P*X - h_x*X ) * dt #used a different varible other than i
		dP <- ( P*(c*(a_x*X+a_y*Y)-d_p)*(1-P/K_p) - h_p*P ) * dt
		X.simu2[i] <- X.simu2[i-1] + dX
		P.simu2[i] <- P.simu2[i-1] + dP	
	}
	
	Xstarset[j] <- X.simu2[length(tset2)] #these are holding vectors for equilibrium values
	Pstarset[j] <- P.simu2[length(tset2)]
	
}
plot(h_xset,Pstarset,type='l',lwd=2,col=Pcol,las=1,xlab='Prey Hunting, H',ylab='Stable equilibria of predator, P*')

plot(h_xset,Xstarset,type='l',lwd=2,col=Xcol,las=1,xlab='Prey Hunting, H',ylab='Stable equilibria of focal prey, X*')


```

