---
title: "Tick and Host SIS"
author: "sbsambado"
date: "4/7/2020"
output: html_document
---
```{r}
#library(deSolve)
SISvector <- function(dt, inits, parms) {
  with(as.list(c(parms, inits)), {
  dS = - (beta*S*V)/(S + I) + gamma*I # S + I = N_host
  dI = (beta*S*V)/(S + I) - gamma*I
  dU = - (alpha*U*I)/(S + I) + b*U - mu*U # U + V = N_vector
  dV = (alpha*U*I)/(S + I) + b*V - mu*V
  
  return(list(c(dS, dI, dU, dV)))
  })
}

dt <- seq(0, 150, 1)

S0 = 99
I0 = 1
U0 = 175 # infected vectors
V0 = 25 # infected vectors

inits <- c(S = S0, I = I0, U = U0,V = V0)

  beta = 0.8 # inoculation # .6
  alpha = 0.5  # acquisition # .5
  gamma = 0.6 # host turnover I > S # .5
  b = 0.2 # birth of vectors #.1
  mu = 0.2 # death of vectors # .15

parms = c(beta = beta, alpha = alpha, gamma = gamma, b = b, mu = mu) 


model.out <- as.data.frame(ode(y = inits, times = dt, func = SISvector, parms = parms))
tail(model.out)

matplot(model.out[,-1],
        type = 'l', xlab = 'time', ylab = 'Population',
        lty = 1:2, col = c('green', 'green', 'blue', 'blue'),
        lwd = 2)
legend('topright', legend = c('U hosts', 'I host', 'U vector', 'I vector'),
        col = c('green', 'green',  'blue', 'blue'), lwd = 2, lty = 1:2, cex = 0.8)



times = seq(0,30, 0.1)


# results = lsoda(initial_values, times, SIS.model.tick.host, parameters)
# colnames(results) = c('time', 'susceptible host', 'infected host', 'susceptible tick', 'infected tick')
# head(results)  
#   
# plot(results[, 'time'], results[,'susceptible host'], type = 'l', col = 'blue', 
#      xlab = 'time', ylab = 'abundance', ylim = c(0,101), lty = 1)
# lines(results[,'time'], results[,'infected host'], type = 'l', col = 'blue', lty = 2)
# lines(results[,'time'], results[,'susceptible tick'], type = 'l', col = 'red', lty = 1)
# lines(results[,'time'], results[,'infected tick'], type = 'l', col = 'red', lty = 2)
# legend('topleft', legend = c('U hosts', 'I host', 'U vector', 'I vector'),
#        col = c('blue', 'blue', 'red', 'red'), lwd = 2, lty = c(1,2,1,2), cex = 0.6)
```

```{r change birth rate of vector}
bVec <- seq(0, .8, by = 0.01)
dt <- seq(0, 500, 1)

SISVectorFunc <- function(x) {
  parms <- c(alpha = alpha, beta = beta, gamma = gamma, b = b, mu = mu)
  
  model.out2 <- as.data.frame(ode(y = inits, times = dt, func = SISvector, parms = parms))
  
  # extract value for I from last time point t = 500 and calculate % of infected hosts
  infectFinal <- (model.out2$I[501]/ (S0 + I0))*100
  return(c(x, infectFinal))
}

# appy each element of bVec to function SISVectorFunc
# sapply is now a 2 x 21 column matrix
# t() transposes this matrix to become a 21 row x 2 column
# make data frame object and rename
bResults <- as.data.frame(t(sapply(bVec, SISVectorFunc, simplify = TRUE)))
names(bResults) <- c("b", "I")

plot( I ~ b, data = bResults,
      type = 'b', lwd = 2, col = 'green', 
      ylab = 'Percent infected hosts',
      xlab = 'vector birth rate (b)')

### change death rate
muVec <- seq(0, .8, by = 0.01)
dt <- seq(0, 500, 1)

SISVectorFunc <- function(x) {
  parms <- c(alpha = alpha, beta = beta, gamma = gamma, b = b, mu = mu)
  
  model.out3 <- as.data.frame(ode(y = inits, times = dt, func = SISvector, parms = parms))
  
  # extract value for I from last time point t = 500 and calculate % of infected hosts
  infectFinal <- (model.out3$I[501]/ (S0 + I0))*100
  return(c(x, infectFinal))
}

# appy each element of bVec to function SISVectorFunc
# sapply is now a 2 x 21 column matrix
# t() transposes this matrix to become a 21 row x 2 column
# make data frame object and rename
muResults <- as.data.frame(t(sapply(muVec, SISVectorFunc, simplify = TRUE)))
names(muResults) <- c("mu", "I")

plot( I ~ mu, data = muResults,
      type = 'b', lwd = 2, col = 'blue', 
      ylab = 'Percent infected hosts',
      xlab = 'vector birth rate (b)')

```

